name: Generic System Image Builder

on:
  workflow_dispatch:
    
env:
    mkdir pixel
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
       - name: Repo fetching...
         uses: actions/checkout@main
           
       - name: Setting up environment...
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Cloning repo...
         run: git clone https://github.com/ponces/treble_build_pe -b thirteen
       
       - name: Installing requirements
         run: |
              sudo chmod -R 777 Pixel
              cd Pixel
              sudo bash treble_build_pe/build.sh
           
       - name: Cleaning output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/

       - name: Uploading AB 
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_AB
              
           
